### ISSUE TITLE
Voucher: no update of View "Finanzstatus" if a voucher code is entered the first time

### ISSUE THREAD

**Issue by shreaker** [shreaker/Secure_Software_Demo#12]
Only problem in view for the **first** voucher code which is entered. See right sidebar.
Money transfer works fine -> see "Umsätze anzeigen"

**Comment by faryon93** [comment]
due to background processing of "money transfers" the account balance may not be up to date when the page is loaded after clicking the submit button. Another page reload is necessary to update the balance.

this is not directly wanted behavior, but in my opinion its not a show stopper. if you try real online banking sites, than you notice that the update of your account balance may take up to one day.

**Comment by shreaker** [comment]
Closing issue, because this behavior is not a problem in fact.
